# GET https://google.com

# GET http://127.0.0.1:3000

# POST http://localhost:3000/login
# content-Type: application/json

# {
#     "username": "creed",
#     "password": "123456"
# }

# GET http://localhost:3000/products

# ###
# GET http://localhost:3000/product/{id}

# ###
# PUT http://localhost:3000/product/{id}
# content-Type: application/json

# {
#     "name": "Glass",
#     "price": "9000"
# }

# ###
# POST http://localhost:3000/product
# content-Type: application/json

# {
#     "name": "Glass cup",
#     "price": "5000"
# }

# ###
# DELETE http://localhost:3000/product/{id}

# GET http://localhost:3000/products

# ###
# GET http://localhost:3000/products/668005252c13d8250471e5a6

# ###
# PUT http://localhost:3000/products/6680037c2c13d8250471e5a2
# content-Type: application/json

# {
#    "productName": "Glass updated",
#     "productPrice": "120000"
# }

# ###
# POST http://localhost:3000/products
# content-Type: application/json

# {
#     "productName": "House Duplex",
#     "productPrice": "3600000000"
# }

# ###
# DELETE http://localhost:3000/products/6680bf36c16c0d825b8593d2


# ###
# POST http://localhost:3000/user/register
# content-Type: application/json

# {
#     "fullName": "SLide Green",
#     "email": "slide@gmail.com",
#     "password": "jun66"
# }

# ###
# POST http://localhost:3000/user/login
# content-Type: application/json

# {
#     "email": "slide@gmail.com",
#     "password": "jun66"
# }




###
POST http://localhost:3000/auth/register
Content-Type: application/json

    # "email": "chideraamazingkids@gmail.com",
{
    "fullName": "Egbon Adu",
    "email": "4chimabika@gmail.com",
    "password": "creed"
}

###
# DELETE http://localhost:3000/products/6680bf36c16c0d825b8593d2


# ###
# POST http://localhost:3000/user/register
# content-Type: application/json

# {
#     "fullName": "SLide Green",
#     "email": "slide@gmail.com",
#     "password": "jun66"
# }

# ###
# POST http://localhost:3000/user/login
# content-Type: application/json

# {
#     "email": "slide@gmail.com",
#     "password": "jun66"
# }

